import { defineArrayMember, defineField, defineType } from 'sanity';
import { displayOrder, externalUrl, orderedDocument, requiredString, strings, text, translationsField } from './fields';

export const project = defineType({
  name: 'project', title: 'Project', type: 'document',
  ...orderedDocument,
  groups: [
    { name: 'overview', title: 'Overview', default: true },
    { name: 'story', title: 'Case study' },
    { name: 'media', title: 'Images & gallery' },
    { name: 'visibility', title: 'Homepage & ordering' },
    { name: 'links', title: 'Links' },
  ],
  fields: [
    { ...requiredString('title', 'Full project title'), group: 'overview' },
    defineField({ name: 'shortTitle', title: 'Short display title', type: 'string', group: 'overview', description: 'Optional. Cards and the detail heading use this; otherwise they use the full title.' }),
    defineField({ name: 'slug', title: 'URL slug', type: 'slug', group: 'overview',
      options: { source: 'title', maxLength: 96 },
      description: 'Click Generate. This becomes /projects/your-slug. Keep published slugs stable to preserve existing links.',
      validation: (rule) => rule.required().custom((value) => !value?.current || /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value.current) ? true : 'Use lowercase letters, numbers, and single hyphens only.'),
    }),
    { ...requiredString('category', 'Category'), group: 'overview' },
    { ...requiredString('period', 'Displayed project period'), group: 'overview', description: 'For example: June 2026 — July 2026. Preserve approximate dates as text.' },
    defineField({ name: 'projectDate', title: 'Project date', type: 'date', group: 'overview', description: 'Optional exact date. The displayed period remains the text above.' }),
    { ...text('summary', 'Short description'), group: 'overview', validation: (rule) => rule.required() },
    { ...strings('stack', 'Technologies'), group: 'overview', description: 'Add a technology per item. Drag to reorder the badges.' },
    { ...text('description', 'Full project introduction'), group: 'story', validation: (rule) => rule.required() },
    defineField({ name: 'content', title: 'Additional rich text', type: 'richContent', group: 'story', description: 'Optional formatted content below the introduction.' }),
    { ...text('challenge', 'Challenge'), group: 'story' },
    { ...text('approach', 'Approach'), group: 'story' },
    { ...text('outcome', 'Outcome'), group: 'story' },
    defineField({ name: 'sections', title: 'Additional case-study sections', type: 'array', group: 'story', of: [defineArrayMember({ type: 'caseStudySection' })] }),
    { ...strings('highlights', 'Implementation highlights'), group: 'story' },
    defineField({ name: 'metrics', title: 'Project metrics', type: 'array', group: 'story', of: [defineArrayMember({ type: 'metric' })], description: 'Drag to order. The first three appear beside the project heading. Drag to choose the three displayed metrics; additional values remain stored here.' }),
    defineField({ name: 'coverImage', title: 'Cover image', type: 'portfolioImage', group: 'media', description: 'Upload or select an asset. Used on the project card and above the case study.' }),
    defineField({ name: 'gallery', title: 'Screenshot gallery', type: 'array', group: 'media', of: [defineArrayMember({ type: 'portfolioImage' })], options: { layout: 'grid' }, description: 'Upload multiple screenshots. Drag items to set their display order. Each image supports alt text, caption, crop, and hotspot.' }),
    { ...text('galleryDescription', 'Gallery introduction'), group: 'media' },
    defineField({ name: 'featured', title: 'Featured project', type: 'boolean', group: 'visibility', initialValue: false, description: 'Promote this project above other homepage projects. The first featured project uses the existing large card.' }),
    defineField({ name: 'featuredOrder', title: 'Featured order', type: 'number', group: 'visibility', initialValue: 100, validation: (rule) => rule.integer().min(0), hidden: ({ document }) => !document?.featured, description: 'Lower numbers appear first among featured projects.' }),
    { ...displayOrder, group: 'visibility' },
    defineField({ name: 'showOnHomepage', title: 'Show on homepage', type: 'boolean', group: 'visibility', initialValue: true, description: 'Hide the homepage card while retaining the published detail page.' }),
    { ...externalUrl('githubUrl', 'GitHub URL'), group: 'links' },
    { ...externalUrl('demoUrl', 'Live / demo URL'), group: 'links' },
    { ...translationsField([['title', 'Title', 'string'], ['shortTitle', 'Short title', 'string'], ['summary', 'Short description', 'text'], ['description', 'Introduction', 'text'], ['content', 'Content', 'richContent'], ['challenge', 'Challenge', 'text'], ['approach', 'Approach', 'text'], ['outcome', 'Outcome', 'text']]), group: 'story' },
  ],
  preview: { select: { title: 'title', subtitle: 'category', media: 'coverImage' } },
});
