import type { PortableTextBlock } from '@portabletext/types';

export type Metric = { value: string; label: string };
export type ProjectMedia = {
  src: string;
  alt: string;
  width: number;
  height: number;
  caption: string;
  blurDataURL?: string;
};
export type Project = {
  slug: string;
  title: string;
  shortTitle: string;
  period: string;
  projectDate?: string;
  category: string;
  summary: string;
  description: string;
  content: PortableTextBlock[];
  stack: string[];
  metrics: Metric[];
  highlights: string[];
  challenge: string;
  approach: string;
  outcome: string;
  sections: { _key: string; title: string; body: string }[];
  coverImage?: ProjectMedia;
  gallery: ProjectMedia[];
  galleryDescription: string;
  featured: boolean;
  displayOrder: number;
  featuredOrder: number;
  showOnHomepage: boolean;
  githubUrl?: string;
  demoUrl?: string;
};
export type Profile = {
  name: string; role: string; location: string; email: string; phone: string;
  initials: string; intro: string; about: string; heroHeadline: string;
  heroEyebrow: string; aboutTagline: string; experienceIntro: string;
  heroPhoto?: ProjectMedia; aboutPhoto?: ProjectMedia;
  whatsappNumber?: string; whatsappMessage?: string;
  linkedinUrl?: string; githubUrl?: string; pddiktiUrl?: string;
  cv?: { url: string; filename: string };
  cvUrl?: string;
  instagramUrl?: string;
  roles?: string[];
  aboutShort?: string;
  birthPlace?: string;
  birthDate?: string;
  heightCm?: number;
  itExperienceStartDate?: string;
  volunteerImages?: ProjectMedia[];
  technicalGroups?: { title: string; items: string[] }[];
};
export type SkillGroup = { _id: string; title: string; items: string[]; description?: string; image?: ProjectMedia };
export type Experience = { _id: string; company: string; role: string; period: string; bullets: string[]; stack: string[]; image?: ProjectMedia; gallery: ProjectMedia[] };
export type Education = { _id: string; school: string; degree: string; period: string; gpa: string; coursework: string[]; pddiktiUrl?: string };
export type Publication = { _id: string; title: string; journal: string; issue: string; date: string; doi: string };
export type Activity = {
  _id: string; title: string; slug: string; summary: string; description: string;
  content: PortableTextBlock[]; period: string; date?: string; role: string;
  organization: string; location: string; coverImage?: ProjectMedia; gallery: ProjectMedia[];
  metrics: Metric[]; highlights: string[]; externalUrl?: string; displayOrder: number;
};
export type Certification = { _id: string; title: string; issuer: string; date: string; image?: ProjectMedia; verificationUrl?: string };
export type Portfolio = {
  profile: Profile;
  heroMetrics: Metric[];
  projects: Project[];
  experiences: Experience[];
  educations: Education[];
  publications: Publication[];
  skills: SkillGroup[];
  softSkills: string[];
  community: Activity[];
  certifications: Certification[];
  languages: { name: string; level: string }[];
};
